global:
  # How frequently to scrape targets
  scrape_interval:     10s
  # How frequently to evaluate rules
  evaluation_interval: 10s

# A list of scrape configurations that specifies a set of
# targets and parameters describing how to scrape them.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - node_exporter:9100
  - job_name: 'prom_middleware'
    scrape_interval: 5s
    static_configs:
      - targets:
          - prom_middleware:9091
  - job_name: 'prom_go_app'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:8080"